### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [MMEnter/CompactView#10]
What license is this code under? I'm not sure about contributing under the possibility that this could become paid/closed-source later.

**Comment by MMEnter** [comment]
Sorry, I have no experience with this. I want to keep it open to everybody to contribute and I am not interested in closing it down or getting paid. Is there a good/ reliable resource to learn about different licenses?

**Comment by ghost** [comment]
@MMEnter See GitHub's https://choosealicense.com/ . It covers all the bases when it comes to choosing a license.

**Comment by MMEnter** [comment]
Thanks @rogersachan I read this: https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project and think that the MIT License is the right choice.

**Comment by ghost** [comment]
I think that's a good fit for the project.
